language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
addons:
  ssh_known_hosts:
  - 138.91.114.14
before_install:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- cp .travis/deploy_rsa ~/.ssh/deploy_rsa
- chmod 600 ~/.ssh/deploy_rsa
- ssh-add ~/.ssh/deploy_rsa
- npx npm-force-resolutions
install:
- npm install
script:
- npm run test
- CI=false yarn build
deploy:
- provider: script
  skip_cleanup: true
  script: bash .travis/deploy.sh
  on:
    branch: master
